version: "3"
services:
    frontend:
				# image: sunwoo005/docker-frontend (도커허브에 저장된 이미지)
				# mem_limit: 128m
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
        stdin_open: true

    nginx:
				# image: sunwoo005/docker-nginx
				# mem_limit: 128m
				links:
					- frontend
					- backend
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "3000:80"

    backend:
				# image: sunwoo005/docker-backend
				# mem_limit: 128m
        build:
            dockerfile: Dockerfile.dev
            context: ./backend
        container_name: app_backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: sunwoo005
            MYSQL_DATABASE: myapp
            MYSQL_PORT: 3306

    # mysql:
    #     build: ./mysql
    #     restart: unless-stopped
    #     container_name: app_mysql
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - ./mysql/mysql_data:/var/lib/mysql
    #         - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    #     environment:
    #         MYSQL_ROOT_PASSWORD: sunwoo
    #         MYSQL_DATABASE: myapp
